spring.application.name=ahorros
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AhorrosDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${SA_PASSWORD}
app.carga.habilitada=false 
app.carga.catalogos=../db/datos/catalogos.xml
app.carga.datos=../db/datos/no_catalogos.xml
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
