spring.application.name=ahorros
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AhorrosDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${SA_PASSWORD}
